### ISSUE TITLE
Generate Colleges

### ISSUE THREAD

**Issue by th3pi** [th3pi/CS370-Team-TBA#13]
Mock colleges need to be generated. These mock colleges are required to perform tests. Below are the objectives of this task:

- [x] Generate at least 4 colleges
- [x] Each college must contain the following fields
  - collegeCode (Unique college identification number)
  - name (College name ex. Queens College, St. Johns University)

**Comment by compsci6** [comment]
did you want them as txt files or a class to randomly generate the data

**Comment by th3pi** [comment]
@compsci6 you'd have to use the Firebase Integration that has been set up for the App. The master branch contains the firebase integration.

**Comment by th3pi** [comment]
Colleges will not be implemented due to time and resource constraints
